import type { PublicEvent } from "@/types";

export const SEED_EVENTS: PublicEvent[] = [
  {
    _id: "evt-kolkata-info-session",
    title: "Kickoff Info Session",
    tag: "Info Session",
    date: "Oct 12, 2026 • 10:00 AM",
    startDate: "2026-10-12T10:00:00.000Z",
    endDate: "2026-10-12T12:00:00.000Z",
    venue: "Heritage Central Auditorium, Block B",
    description: "Official OnCampus season kickoff and briefing. Discover this year's global theme, understand the judging criteria, and connect with fellow changemakers from various engineering departments.",
    registrationStatus: "open",
    registrationDeadline: "Oct 10, 2026",
    minTeamMembers: 3,
    maxTeamMembers: 5,
    link: "https://hultprize.org",
  },
  {
    _id: "evt-design-thinking-sprint",
    title: "Social Venture Design Sprint",
    tag: "Workshop",
    date: "Nov 05, 2026 • 02:00 PM",
    startDate: "2026-11-05T14:00:00.000Z",
    endDate: "2026-11-05T18:00:00.000Z",
    venue: "Design Thinking Studio, HITK Campus",
    description: "Hands-on rapid prototyping and business model canvas workshop. Learn how to translate technical innovation into sustainable, revenue-generating social enterprise models.",
    registrationStatus: "open",
    registrationDeadline: "Nov 03, 2026",
    minTeamMembers: 3,
    maxTeamMembers: 5,
  },
  {
    _id: "evt-oncampus-grand-finals",
    title: "OnCampus Grand Pitch Finals",
    tag: "Flagship",
    date: "Dec 18, 2026 • 09:30 AM",
    startDate: "2026-12-18T09:30:00.000Z",
    endDate: "2026-12-18T17:00:00.000Z",
    venue: "Main Heritage Auditorium & Innovation Plaza",
    description: "The premier OnCampus pitch event. Finalist teams present their breakthrough social ventures to an esteemed panel of venture capitalists, angel investors, and industry executives for the ticket to the Global Summits.",
    registrationStatus: "extended",
    registrationDeadline: "Dec 05, 2026",
    minTeamMembers: 3,
    maxTeamMembers: 5,
  },
];