import { TeamMember, TeamSectionConfig } from "@/types";

export const TEAM_SECTIONS: TeamSectionConfig[] = [
  {
    key: "faculty_coordinator",
    title: "Faculty Coordinator",
    subtitle: "Faculty Mentorship & Guidance",
    badge: "Faculty",
    accentColor: "#38bdf8",
    gradientClass: "from-sky-400 via-blue-500 to-indigo-600",
    borderClass: "border-sky-500/40 hover:border-sky-400",
    description:
      "Guiding academic alignment, institutional mentorship, student leadership development, and strategic liaison for Hult Prize OnCampus at Heritage Institute of Technology.",
  },
  {
    key: "cd",
    title: "Campus Director",
    subtitle: "Executive Leadership",
    badge: "CD",
    accentColor: "#f20089",
    gradientClass: "from-amber-400 via-[#f20089] to-purple-600",
    borderClass: "border-amber-500/40 hover:border-[#f20089]",
    description:
      "Steering the overall strategic vision, university relations, and international liaison for Hult Prize OnCampus at Heritage Institute of Technology.",
  },
  {
    key: "dcd",
    title: "Deputy Campus Director",
    subtitle: "Executive Co-Lead",
    badge: "DCD",
    accentColor: "#00d2ff",
    gradientClass: "from-sky-400 via-blue-500 to-[#f20089]",
    borderClass: "border-sky-500/40 hover:border-sky-400",
    description:
      "Co-leading strategic planning, cross-team synchronization, and high-impact operational delivery across all sub-committees.",
  },
  {
    key: "workshop",
    title: "Workshop & Team Management",
    subtitle: "Mentorship & Ideation",
    badge: "Workshops",
    accentColor: "#f59e0b",
    gradientClass: "from-amber-400 to-orange-600",
    borderClass: "border-amber-500/30 hover:border-amber-400",
    description:
      "Curating specialized startup bootcamps, founder clinics, masterclasses, ideation workshops, and synchronizing internal team operations.",
  },
  {
    key: "event_management",
    title: "Event Management",
    subtitle: "Operations & Logistics",
    badge: "Events",
    accentColor: "#10b981",
    gradientClass: "from-emerald-400 to-teal-600",
    borderClass: "border-emerald-500/30 hover:border-emerald-400",
    description:
      "Planning, venue coordination, timeline management, stage operations, and frictionless production for the flagship OnCampus competition.",
  },
  {
    key: "social_pr",
    title: "Social Media PR & Editing",
    subtitle: "Public Relations & Editorial",
    badge: "PR & Media",
    accentColor: "#ec4899",
    gradientClass: "from-pink-500 via-rose-500 to-purple-600",
    borderClass: "border-pink-500/30 hover:border-pink-400",
    description:
      "Driving social media presence, student engagement, official press releases, copywriting, and multimedia storytelling.",
  },
  {
    key: "photography",
    title: "Photography",
    subtitle: "Visual Documentation",
    badge: "Media",
    accentColor: "#8b5cf6",
    gradientClass: "from-violet-500 via-purple-500 to-indigo-600",
    borderClass: "border-purple-500/30 hover:border-purple-400",
    description:
      "Capturing the photographic journey, high-impact portraits, event coverage, and visual documentation across all milestones.",
  },
  {
    key: "tech",
    title: "Technical",
    subtitle: "Platform & Engineering",
    badge: "Engineering",
    accentColor: "#38bdf8",
    gradientClass: "from-cyan-400 via-sky-500 to-indigo-600",
    borderClass: "border-sky-500/30 hover:border-sky-400",
    description:
      "Architecting the official web application, secure participant onboarding, automated email verification, and digital platforms.",
  },
  {
    key: "design",
    title: "Design",
    subtitle: "Creative & Brand Identity",
    badge: "Creative",
    accentColor: "#f20089",
    gradientClass: "from-[#f20089] via-pink-500 to-purple-600",
    borderClass: "border-[#f20089]/30 hover:border-[#f20089]",
    description:
      "Crafting the visual identity, motion graphics, promotional banners, stage brand assets, and user interface aesthetics.",
  },
  {
    key: "judges_support",
    title: "Judges Support",
    subtitle: "Jury Liaison & Hospitality",
    badge: "Jury Liaison",
    accentColor: "#06b6d4",
    gradientClass: "from-teal-400 via-cyan-500 to-blue-600",
    borderClass: "border-cyan-500/30 hover:border-cyan-400",
    description:
      "Coordinating esteemed jury panels, evaluation protocols, scoring rubrics, deliberations, and VIP judge hospitality.",
  },
];

/**
 * Official team members roster.
 * Each member with a `slug` automatically has:
 * 1. An interactive card on the /team page
 * 2. A dedicated 3D Lanyard ID Card page at /team/[slug]
 */
export const INITIAL_TEAM_MEMBERS: TeamMember[] = [
  // Faculty Mentorship
  {
    id: "jhalak-dutta",
    slug: "jhalak-dutta",
    name: "Prof. Jhalak Dutta",
    role: "Faculty Coordinator",
    category: "faculty_coordinator",
    department: "Computer Science & Engineering (CSE)",
    academicYear: "Faculty Coordinator",
    image: "/team/placeholder.png",
    bio: "Assistant Professor in the Department of Computer Science & Engineering at Heritage Institute of Technology. Guiding and mentoring student entrepreneurs and researchers through Hult Prize OnCampus at HITK.",
    socials: {
      linkedin: "https://www.linkedin.com/in/jhalak-dutta",
      email: "jhalak.dutta@heritageit.edu",
    },
    featured: true,
  },

  // Executive Leadership
  {
    id: "pratyush-sarkar",
    slug: "pratyush-sarkar",
    name: "Pratyush Sarkar",
    role: "Campus Director",
    category: "cd",
    department: "Electronics & Communication Engineering (ECE)",
    academicYear: "Batch of 2028",
    image: "/team/pratyush-sarkar.jpeg",
    bio: "“If your dreams don’t scare you, they are not big enough “",
    socials: {
      email: "pratyushsarkar1417@gmail.com",
      instagram: "https://www.instagram.com/_pratyush_sarkar_0206?stkn=OTUzaTlmZGl5a2xi&utm_source=qr",
      linkedin: "https://www.linkedin.com/in/pratyush-sarkar-322bb2285?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      x: "https://x.com/pratyush0204?s=11",
      portfolio: "https://share.google/7kVPcvjgeUQOUJaDy",
    },
    featured: true,
  },
  {
    id: "bhoomi-ladia",
    slug: "bhoomi-ladia",
    name: "Bhoomi Ladia",
    role: "Deputy Campus Director",
    category: "dcd",
    department: "Computer Science & Engineering (CSE)",
    academicYear: "Final Year",
    image: "/team/bhoomi.jpg",
    bio: "Empowering visionary student entrepreneurs to solve the world's most pressing challenges. Leading communities and bringing Hult Prize to new heights at Heritage Institute of Technology.",
    socials: {
      linkedin: "https://linkedin.com/in/bhoomi-ladia",
      instagram: "https://instagram.com/bhoomi_ladia",
      email: "bhoomi@hultprizehitk.com",
    },
    featured: true,
  },

  // 1. Workshop and Team Management
  {
    id: "oindrayee-chaudhury",
    slug: "oindrayee-chaudhury",
    name: "Oindrayee Chaudhury",
    role: "Team Lead",
    category: "workshop",
    department: "Computer Science & Engineering (CSE)",
    academicYear: "3rd Year",
    image: "/team/oindrayee-chaudhury.jpeg",
    bio: "Grace in style , Grit in business",
    socials: {
      email: "oindrayeechaudhury@gmail.com",
      instagram: "https://www.instagram.com/_oxndrxyeeee_?stkn=bjN4dGM2ZTRrcmRs&utm_source=qr",
      linkedin: "https://www.linkedin.com/in/oindrayee-chaudhury-98686a419?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      snapchat: "https://snapchat.com/add/oindrayee_15",
    },
    featured: true,
  },
  {
    id: "anjistha-mukhopadhyay",
    slug: "anjistha-mukhopadhyay",
    name: "Anjistha Mukhopadhyay",
    role: "Team Lead",
    category: "workshop",
    department: "Electronics & Communication Engineering (ECE)",
    image: "/team/anjistha-mukhopadhyay.jpg",
    bio: "Curating high-impact startup workshops, mentorship clinics, and cross-team synchronization.",
    featured: true,
  },
  {
    id: "sarika-misra",
    slug: "sarika-misra",
    name: "Sarika Misra",
    role: "Team Member",
    category: "workshop",
    department: "Computer Science & Engineering (CSE)",
    academicYear: "2nd Year",
    image: "/team/sarika-misra.jpg",
    bio: "Curiosity is my capital",
    socials: {
      email: "sarikamisra9g@gmail.com",
      instagram: "https://www.instagram.com/sarikxa._?stkn=dHMwZzA2aThreGkz",
      linkedin: "https://www.linkedin.com/in/sarika-misra-032596384?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      github: "https://github.com/sarikamisra-cloud",
    },
  },
  {
    id: "arkaja-chatterjee",
    slug: "arkaja-chatterjee",
    name: "Arkaja Chatterjee",
    role: "Team Member",
    category: "workshop",
    department: "Biotechnology",
    academicYear: "Batch of 2029",
    image: "/team/arkaja-chatterjee.jpg",
    bio: "If you cannot do great things, do small things in a great way.",
    socials: {
      email: "chatterjeearkaja@gmail.com",
      instagram: "https://instagram.com/arkajachatterjee",
    },
  },
  {
    id: "avigyan-kishor-das",
    slug: "avigyan-kishor-das",
    name: "Avigyan Kishor Das",
    role: "Team Member",
    category: "workshop",
    department: "Electronics & Communication Engineering (ECE)",
    academicYear: "2nd Year",
    image: "/team/avigyan-kishor-das.jpg",
    bio: '"Innovation distinguishes between a leader and a follower." — Steve Jobs',
    socials: {
      email: "avigyankishordas@gmail.com",
      instagram: "https://www.instagram.com/imavigyan/",
      linkedin: "https://www.linkedin.com/in/avigyan-kishor-das-b001bb3b9/",
      github: "https://github.com/Avigyan09",
    },
  },

  // 2. Event Management
  {
    id: "anshuman-katyan-jha",
    slug: "anshuman-katyan-jha",
    name: "Anshuman Katyan Jha",
    role: "Team Lead",
    category: "event_management",
    department: "Computer Science & Engineering (CSE)",
    academicYear: "3rd Year",
    image: "/team/anshuman-katyan-jha.jpeg",
    bio: "i'm not great at the advice. can I interest you in a sarcastic comment?",
    socials: {
      email: "akjha.1207@gmail.com",
      instagram: "https://www.instagram.com/shutterbug._.raw",
      linkedin: "https://www.linkedin.com/in/anshuman-katyan-jha-142a4a280/",
      x: "https://x.com/JhaKatyan",
      github: "https://github.com/anshuman1207",
    },
    featured: true,
  },
  {
    id: "soumyadeep-das-mandal",
    slug: "soumyadeep-das-mandal",
    name: "Soumyadeep Das Mandal",
    role: "Team Lead",
    category: "event_management",
    department: "Electronics & Communication Engineering (ECE)",
    academicYear: "3rd Year",
    image: "/team/soumyadeep-das-mandal.jpg",
    bio: "Dream is not that which you see while sleeping, it is something that doesn't let you sleep. Dream big, Dream Unique !",
    socials: {
      email: "contact.sdasmandal@gmail.com",
      instagram: "https://www.instagram.com/sdm_myself",
      linkedin: "https://www.linkedin.com/in/martaindeep20",
      x: "https://x.com/martian_deep",
      github: "https://github.com/martiandeep20",
    },
    featured: true,
  },
  {
    id: "datyatreya-ray",
    slug: "datyatreya-ray",
    name: "Datyatreya Ray",
    role: "Team Member",
    category: "event_management",
    department: "CSE - IoT & Cyber Security (IoTCS)",
    academicYear: "2nd Year",
    image: "/team/datyatreya-ray.jpg",
    bio: "Failure is the point from where you start winning",
    socials: {
      email: "datyatreya.ray.iotcs29@heritageit.edu.in",
      instagram: "https://www.instagram.com/d_on_therun/",
      linkedin: "https://www.linkedin.com/in/datyatreya-ray-9094843b6?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
  },
  {
    id: "sania-parvin",
    slug: "sania-parvin",
    name: "Sania Parvin",
    role: "Team Member",
    category: "event_management",
    department: "Biotechnology",
    academicYear: "2nd Year",
    image: "/team/sania-parvin.jpg",
    bio: "Don't wait for opportunities; build the ones you wish existed.",
    socials: {
      email: "saniaparvin2006@gmail.com",
      instagram: "https://www.instagram.com/saniaparvin17?stkn=anBvd3FmYnFjczNv",
      linkedin: "https://www.linkedin.com/in/sania-parvin-87263b343?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
  },

  // 3. Social Media PR and Editing
  {
    id: "soha-alam-mondal",
    slug: "soha-alam-mondal",
    name: "Soha Alam Mondal",
    role: "Team Lead",
    category: "social_pr",
    department: "CSE - Artificial Intelligence & Machine Learning (AIML)",
    academicYear: "3rd Year",
    image: "/team/soha-alam-mondal.jpeg",
    bio: "Creating with intentions",
    socials: {
      email: "soha.am2013@gmail.com",
      instagram: "https://instagram.com/itzsohaaa",
      linkedin: "https://www.linkedin.com/in/soha-alam-mondal-01536031a?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      github: "https://github.com/itzsohaaa",
    },
    featured: true,
  },
  {
    id: "kaustavi-mullick",
    slug: "kaustavi-mullick",
    name: "Kaustavi Mullick",
    role: "Team Lead",
    category: "social_pr",
    department: "Biotechnology",
    academicYear: "3rd Year",
    image: "/team/kaustavi-mullick.jpg",
    bio: "“Start before you’re ready, because the future is built, not predicted.”",
    socials: {
      email: "kaustavimullick@gmail.com",
      instagram: "https://www.instagram.com/kaustavimullick?stkn=MXJxcDdqa2hycjR1Yg%3D%3D&utm_source=qr",
      linkedin: "https://www.linkedin.com/in/kaustavi-mullick-961395329?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
    },
    featured: true,
  },
  {
    id: "amit-majumder",
    slug: "amit-majumder",
    name: "Amit Majumder",
    role: "Team Member",
    category: "social_pr",
    department: "Electronics & Communication Engineering (ECE)",
    bio: "Curating engaging digital campaigns, reels, and community outreach for Hult Prize HITK.",
  },
  {
    id: "bedantika-sadhukhan",
    slug: "bedantika-sadhukhan",
    name: "Bedantika Sadhukhan",
    role: "Team Member",
    category: "social_pr",
    department: "Biotechnology",
    academicYear: "2nd Year",
    image: "/team/bedantika-sadhukhan.jpeg",
    bio: "broke.",
    socials: {
      email: "bedantika2396@gmail.com",
      instagram: "https://www.instagram.com/bedantika_06?stkn=MXdtNGd3ZTJmcWRkNQ%3D%3D&utm_source=qr",
      linkedin: "https://www.linkedin.com/in/bedantika-sadhukhan-1a92a6386?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
    },
  },
  {
    id: "titli-ray",
    slug: "titli-ray",
    name: "Titli Ray",
    role: "Team Member",
    category: "social_pr",
    department: "CSE - IoT & Cyber Security (IoTCS)",
    bio: "Managing content calendar, digital promotion, and community engagement for Hult Prize HITK.",
  },
  {
    id: "antarika-roy",
    slug: "antarika-roy",
    name: "Antarika Roy",
    role: "Team Member",
    category: "social_pr",
    department: "CSE - Artificial Intelligence & Machine Learning (AIML)",
    academicYear: "2nd Year",
    image: "/team/antarika-roy.jpg",
    bio: "Think. Build. Impact.",
    socials: {
      email: "antarikaroy01@gmail.com",
      instagram: "https://www.instagram.com/antarika_roy?stkn=MXdqaDU2c2tlNDAxeg==",
    },
  },

  // 4. Photography
  {
    id: "subhadeep-chanda",
    slug: "subhadeep-chanda",
    name: "Subhadeep Chanda",
    role: "Team Lead",
    category: "photography",
    department: "Electrical Engineering (EE)",
    academicYear: "3rd Year",
    image: "/team/subhadeep-chanda.jpg",
    bio: "Vision first, excuses never.",
    socials: {
      email: "subhadeepchanda21@gmail.com",
      instagram: "https://www.instagram.com/afunnyguy_?stkn=bXFoaGN3bDdwdDkw",
    },
    featured: true,
  },
  {
    id: "somiyo-roy",
    slug: "somiyo-roy",
    name: "Somiyo Roy",
    role: "Team Lead",
    category: "photography",
    department: "Electronics & Communication Engineering (ECE)",
    academicYear: "3rd Year",
    image: "/team/somiyo-roy.jpg",
    bio: "Success is not just about reaching the top but about enjoying the climb",
    socials: {
      email: "somiyo.roy.ece28@heritageit.edu.in",
      instagram: "https://www.instagram.com/somiyo_roy?stkn=OW9qNXN4amZscWli",
    },
    featured: true,
  },
  {
    id: "utsa-pal",
    slug: "utsa-pal",
    name: "Utsa Pal",
    role: "Team Member",
    category: "photography",
    department: "Computer Science & Engineering (CSE)",
    academicYear: "2nd Year",
    image: "/team/utsa-pal.jpeg",
    bio: "“See differently. Create boldly. Build relentlessly.”",
    socials: {
      email: "utsa.pal2021@gmail.com",
      instagram: "https://www.instagram.com/utso_pal?stkn=YWM2ZTljd3RyYXYw&utm_source=qr",
      linkedin: "https://www.linkedin.com/in/utsa-pal-9ba245341?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
      portfolio: "https://www.instagram.com/the_pixel.pioneers?stkn=MWNtbDVqODBjenBtMg%3D%3D&utm_source=qr",
    },
  },
  {
    id: "suvrojeet-samanta",
    slug: "suvrojeet-samanta",
    name: "Suvrojeet Samanta",
    role: "Team Member",
    category: "photography",
    department: "Civil Engineering",
    academicYear: "2nd Year",
    bio: "Think long term, work quietly, and let the results introduce you",
    socials: {
      email: "samantasuvrojeet@gmail.com",
      instagram: "https://www.instagram.com/samantajeetsuvro?stkn=MWV6aXE4eXJ4eHd5NA==",
      linkedin: "https://www.linkedin.com/in/suvrojeet-samanta-a24ab3438?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
  },

  // 5. Technical
  {
    id: "harsh-raj",
    slug: "harsh-raj",
    name: "Harsh Raj",
    role: "Technical Lead",
    category: "tech",
    department: "CSE - IoT & Cyber Security",
    academicYear: "Final Year",
    image: "/team/harsh.jpg",
    bio: "Transforming ambitious ideas into scalable, beautiful digital platforms and web experiences.",
    socials: {
      linkedin: "https://linkedin.com/in/harsh-raj",
      github: "https://github.com/harsh-raj",
      instagram: "https://instagram.com/harsh_raj",
      email: "harsh@hultprizehitk.com",
    },
    featured: true,
  },
  {
    id: "yogesh-kumar",
    slug: "yogesh-kumar",
    name: "Yogesh Kumar",
    role: "Technical Lead",
    category: "tech",
    department: "Computer Science & Engineering (CSE)",
    academicYear: "3rd Year",
    bio: "Test",
    socials: {
      email: "fbyogesh111@gmail.com",
      linkedin: "https://www.linkedin.com/in/yogesh-kumar-299298260",
      x: "https://x.com/Yoges_ai",
      github: "https://github.com/Coden-inja",
    },
    featured: true,
  },
  {
    id: "aheen-chatterjee",
    slug: "aheen-chatterjee",
    name: "Aheen Chatterjee",
    role: "Team Member",
    category: "tech",
    department: "Computer Science & Business Systems (CSBS)",
    image: "/team/aheen-chatterjee.jpg",
    bio: "Building digital platforms, frontend interfaces, and responsive web systems for Hult Prize HITK.",
  },
  {
    id: "sagar-choudhary",
    slug: "sagar-choudhary",
    name: "Sagar Choudhary",
    role: "Team Member",
    category: "tech",
    department: "Computer Science & Engineering (CSE)",
    image: "/team/sagar-choudhary.jpg",
    bio: "Engineering robust web architecture, portal features, and workflow tools for Hult Prize HITK.",
  },

  // 6. Design
  {
    id: "arunima-dutta",
    slug: "arunima-dutta",
    name: "Arunima Dutta",
    role: "Team Lead",
    category: "design",
    department: "Computer Science & Engineering (CSE)",
    bio: "Leading brand identity, UI design, creative layouts, and stage visual aesthetics.",
    featured: true,
  },
  {
    id: "srija-banerjee",
    slug: "srija-banerjee",
    name: "Srija Banerjee",
    role: "Team Lead",
    category: "design",
    department: "Electronics & Communication Engineering (ECE)",
    image: "/team/srija-banerjee.jpeg",
    bio: "Crafting promotional graphics, motion visuals, and brand assets for Hult Prize HITK.",
    featured: true,
  },
  {
    id: "preksha-baid",
    slug: "preksha-baid",
    name: "Preksha Baid",
    role: "Team Member",
    category: "design",
    department: "Computer Science & Engineering (CSE)",
    academicYear: "2nd Year",
    image: "/team/preksha-baid.jpg",
    bio: "Adapt. React. Readapt. Apt. - M. G. Scott",
    socials: {
      email: "prekshab2007@gmail.com",
      instagram: "https://www.instagram.com/prekzaa_zaa/",
      linkedin: "https://www.linkedin.com/in/preksha-baid-b43522378",
      github: "https://github.com/prekshab2007-cpu",
    },
  },
  {
    id: "soumyadeep-gope",
    slug: "soumyadeep-gope",
    name: "Soumyadeep Gope",
    role: "Team Member",
    category: "design",
    department: "CSE - Data Science (DS)",
    academicYear: "2nd Year",
    image: "/team/soumyadeep-gope.jpeg",
    bio: "Ideas are cheap. Execution is everything.",
    socials: {
      email: "soumya.official.242@gmail.com",
      instagram: "https://www.instagram.com/soumya_d3ep?stkn=Y2U3MmIydWptaGxm",
      linkedin: "https://www.linkedin.com/in/soumyadeep-gope",
      portfolio: "http://redbatcreatives.framer.ai",
    },
  },
  {
    id: "faizan-ahmed",
    slug: "faizan-ahmed",
    name: "Faizan Ahmed",
    role: "Team Member",
    category: "design",
    department: "Computer Science & Business System",
    academicYear: "2nd Year",
    image: "/team/faizan-ahmed.jpg",
    bio: "Think beyond the possible. Build beyond the obvious.",
    socials: {
      email: "faizanahmed24072000@gmail.com",
      instagram: "https://www.instagram.com/introvert_faizan/",
      linkedin: "https://www.linkedin.com/in/faizan-ahmed-5411872b5/",
      x: "https://x.com/FaiXan_Ahm3D",
      github: "https://github.com/FaiXanAhm3D",
      behance: "https://www.behance.net/faizanahmed215/",
    },
  },
  {
    id: "archita-rudra",
    slug: "archita-rudra",
    name: "Archita Rudra",
    role: "Team Member",
    category: "design",
    department: "Computer Science & Engineering (CSE)",
    academicYear: "2nd Year",
    image: "/team/archita-rudra.jpg",
    bio: "Done is better than perfect. Because an imperfect design in the hands of real users will always beat a flawless idea sitting on a hard drive.",
    socials: {
      email: "architarudra2007@gmail.com",
      instagram: "https://www.instagram.com/arxchiii?stkn=MWQ4cTZmdTBhbTh3cA==",
      linkedin: "https://www.linkedin.com/in/archita-r-80302b385",
      github: "https://github.com/architaR07",
    },
  },

  // 7. Judges Support
  {
    id: "swagatam-chatterjee",
    slug: "swagatam-chatterjee",
    name: "Swagatam Chatterjee",
    role: "Team Lead",
    category: "judges_support",
    department: "Electronics & Communication Engineering (ECE)",
    academicYear: "3rd Year",
    image: "/team/swagatam-chatterjee.jpg",
    bio: "Make it exist first, you can make it good later",
    socials: {
      email: "swagatamchat2004@gmail.com",
      instagram: "https://www.instagram.com/swagatam.ch?stkn=ejlkNmN3aGpycWVr",
      linkedin: "https://www.linkedin.com/in/swagatam-chatterjee-341bab333",
    },
    featured: true,
  },
  {
    id: "sohon-ganguly",
    slug: "sohon-ganguly",
    name: "Sohon Ganguly",
    role: "Team Lead",
    category: "judges_support",
    department: "Computer Science & Engineering (CSE)",
    academicYear: "3rd Year",
    image: "/team/sohon-ganguly.png",
    bio: "I feel like I'm in a toilet paper commercial",
    socials: {
      email: "sohongan@gmail.com",
      instagram: "https://www.instagram.com/_.sohon._?stkn=d2tkNGozb2I3dHFk",
      linkedin: "https://www.linkedin.com/in/sohon-ganguly",
      snapchat: "https://snapchat.com/add/sohongan-2811",
    },
    featured: true,
  },
  {
    id: "aditya-roy",
    slug: "aditya-roy",
    name: "Aditya Roy",
    role: "Team Member",
    category: "judges_support",
    department: "Computer Science & Engineering (CSE)",
    academicYear: "2nd Year",
    image: "/team/aditya-roy.jpg",
    bio: "Being myself - Everyone else is taken",
    socials: {
      email: "immortal7aditya@gmail.com",
      instagram: "https://www.instagram.com/_aditya_roy_34/",
      linkedin: "https://www.linkedin.com/in/aditya-roy-a3a345433?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
  },
  {
    id: "satyam-kumar-mishra",
    slug: "satyam-kumar-mishra",
    name: "Satyam Kumar Mishra",
    role: "Team Member",
    category: "judges_support",
    department: "Chemical Engineering (ChE)",
    academicYear: "2nd Year",
    image: "/team/satyam-kumar-mishra.jpg",
    bio: "Trying to be better version of myself.",
    socials: {
      email: "satyam200626@gmail.com",
      instagram: "https://www.instagram.com/its_satyam852_?stkn=MW9rZTcybGtldm9xNg==",
      linkedin: "https://www.linkedin.com/in/satyam-mishra-4080183a8?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    },
  },
];
