import { TeamMember, TeamSectionConfig } from "@/types";

export const TEAM_SECTIONS: TeamSectionConfig[] = [
  {
    key: "faculty_coordinator",
    title: "Faculty Coordinator",
    subtitle: "Faculty Mentorship & Guidance",
    badge: "Faculty",
    accentColor: "#38bdf8",
    gradientClass: "from-sky-400 via-blue-500 to-indigo-600",
    borderClass: "border-sky-500/40 hover:border-sky-400",
    description:
      "Guiding academic alignment, institutional mentorship, student leadership development, and strategic liaison for Hult Prize OnCampus at Heritage Institute of Technology.",
  },
  {
    key: "cd",
    title: "Campus Director",
    subtitle: "Executive Leadership",
    badge: "CD",
    accentColor: "#f20089",
    gradientClass: "from-amber-400 via-[#f20089] to-purple-600",
    borderClass: "border-amber-500/40 hover:border-[#f20089]",
    description:
      "Steering the overall strategic vision, university relations, and international liaison for Hult Prize OnCampus at Heritage Institute of Technology.",
  },
  {
    key: "dcd",
    title: "Deputy Campus Director",
    subtitle: "Executive Co-Lead",
    badge: "DCD",
    accentColor: "#00d2ff",
    gradientClass: "from-sky-400 via-blue-500 to-[#f20089]",
    borderClass: "border-sky-500/40 hover:border-sky-400",
    description:
      "Co-leading strategic planning, cross-team synchronization, and high-impact operational delivery across all sub-committees.",
  },
  {
    key: "workshop",
    title: "Workshop & Team Management",
    subtitle: "Mentorship & Ideation",
    badge: "Workshops",
    accentColor: "#f59e0b",
    gradientClass: "from-amber-400 to-orange-600",
    borderClass: "border-amber-500/30 hover:border-amber-400",
    description:
      "Curating specialized startup bootcamps, founder clinics, masterclasses, ideation workshops, and synchronizing internal team operations.",
  },
  {
    key: "event_management",
    title: "Event Management",
    subtitle: "Operations & Logistics",
    badge: "Events",
    accentColor: "#10b981",
    gradientClass: "from-emerald-400 to-teal-600",
    borderClass: "border-emerald-500/30 hover:border-emerald-400",
    description:
      "Planning, venue coordination, timeline management, stage operations, and frictionless production for the flagship OnCampus competition.",
  },
  {
    key: "social_pr",
    title: "Social Media PR & Editing",
    subtitle: "Public Relations & Editorial",
    badge: "PR & Media",
    accentColor: "#ec4899",
    gradientClass: "from-pink-500 via-rose-500 to-purple-600",
    borderClass: "border-pink-500/30 hover:border-pink-400",
    description:
      "Driving social media presence, student engagement, official press releases, copywriting, and multimedia storytelling.",
  },
  {
    key: "photography",
    title: "Photography",
    subtitle: "Visual Documentation",
    badge: "Media",
    accentColor: "#8b5cf6",
    gradientClass: "from-violet-500 via-purple-500 to-indigo-600",
    borderClass: "border-purple-500/30 hover:border-purple-400",
    description:
      "Capturing the photographic journey, high-impact portraits, event coverage, and visual documentation across all milestones.",
  },
  {
    key: "tech",
    title: "Technical",
    subtitle: "Platform & Engineering",
    badge: "Engineering",
    accentColor: "#38bdf8",
    gradientClass: "from-cyan-400 via-sky-500 to-indigo-600",
    borderClass: "border-sky-500/30 hover:border-sky-400",
    description:
      "Architecting the official web application, secure participant onboarding, automated email verification, and digital platforms.",
  },
  {
    key: "design",
    title: "Design",
    subtitle: "Creative & Brand Identity",
    badge: "Creative",
    accentColor: "#f20089",
    gradientClass: "from-[#f20089] via-pink-500 to-purple-600",
    borderClass: "border-[#f20089]/30 hover:border-[#f20089]",
    description:
      "Crafting the visual identity, motion graphics, promotional banners, stage brand assets, and user interface aesthetics.",
  },
  {
    key: "judges_support",
    title: "Judges Support",
    subtitle: "Jury Liaison & Hospitality",
    badge: "Jury Liaison",
    accentColor: "#06b6d4",
    gradientClass: "from-teal-400 via-cyan-500 to-blue-600",
    borderClass: "border-cyan-500/30 hover:border-cyan-400",
    description:
      "Coordinating esteemed jury panels, evaluation protocols, scoring rubrics, deliberations, and VIP judge hospitality.",
  },
];

/**
 * Official team members roster.
 * Each member with a `slug` automatically has:
 * 1. An interactive card on the /team page
 * 2. A dedicated 3D Lanyard ID Card page at /team/[slug]
 */
export const INITIAL_TEAM_MEMBERS: TeamMember[] = [
  // Faculty Mentorship
  {
    id: "jhalak-dutta",
    slug: "jhalak-dutta",
    name: "Prof. Jhalak Dutta",
    role: "Faculty Coordinator",
    category: "faculty_coordinator",
    department: "Computer Science & Engineering (CSE)",
    academicYear: "Faculty Coordinator",
    bio: "Assistant Professor in the Department of Computer Science & Engineering at Heritage Institute of Technology. Guiding and mentoring student entrepreneurs and researchers through Hult Prize OnCampus at HITK.",
    socials: {
      linkedin: "https://www.linkedin.com/in/jhalak-dutta",
      email: "jhalak.dutta@heritageit.edu",
    },
    featured: true,
  },

  // Executive Leadership
  {
    id: "pratyush-sarkar",
    slug: "pratyush-sarkar",
    name: "Pratyush Sarkar",
    role: "Campus Director",
    category: "cd",
    department: "Executive Directorship",
    academicYear: "Final Year",
    bio: "Steering the overall strategic vision, university relations, and international liaison for Hult Prize OnCampus at Heritage Institute of Technology.",
    socials: {
      linkedin: "https://linkedin.com/in/pratyush-sarkar",
      email: "pratyush@hultprizehitk.com",
    },
    featured: true,
  },
  {
    id: "bhoomi-ladia",
    slug: "bhoomi-ladia",
    name: "Bhoomi Ladia",
    role: "Deputy Campus Director",
    category: "dcd",
    department: "Computer Science & Engineering (CSE)",
    academicYear: "Final Year",
    image: "/team/bhoomi.jpg",
    bio: "Empowering visionary student entrepreneurs to solve the world's most pressing challenges. Leading communities and bringing Hult Prize to new heights at Heritage Institute of Technology.",
    socials: {
      linkedin: "https://linkedin.com/in/bhoomi-ladia",
      instagram: "https://instagram.com/bhoomi_ladia",
      email: "bhoomi@hultprizehitk.com",
    },
    featured: true,
  },

  // 1. Workshop and Team Management
  {
    id: "oindrayee-chaudhury",
    slug: "oindrayee-chaudhury",
    name: "Oindrayee Chaudhury",
    role: "Team Lead",
    category: "workshop",
    department: "Computer Science & Engineering (CSE)",
    bio: "Leading founder bootcamps, ideation masterclasses, and internal team coordination for Hult Prize HITK.",
    featured: true,
  },
  {
    id: "anjistha-mukhopadhyay",
    slug: "anjistha-mukhopadhyay",
    name: "Anjistha Mukhopadhyay",
    role: "Team Lead",
    category: "workshop",
    department: "Electronics & Communication Engineering (ECE)",
    bio: "Curating high-impact startup workshops, mentorship clinics, and cross-team synchronization.",
    featured: true,
  },
  {
    id: "sarika-misra",
    slug: "sarika-misra",
    name: "Sarika Misra",
    role: "Team Member",
    category: "workshop",
    department: "Computer Science & Engineering (CSE)",
    bio: "Organizing founder clinics, masterclasses, and participant onboarding for Hult Prize HITK.",
  },
  {
    id: "arkaja-chatterjee",
    slug: "arkaja-chatterjee",
    name: "Arkaja Chatterjee",
    role: "Team Member",
    category: "workshop",
    department: "Biotechnology (BT)",
    bio: "Facilitating ideation bootcamps, startup mentorship sessions, and team synchronization.",
  },
  {
    id: "avigyan-kishor-das",
    slug: "avigyan-kishor-das",
    name: "Avigyan Kishor Das",
    role: "Team Member",
    category: "workshop",
    department: "Electronics & Communication Engineering (ECE)",
    bio: "Coordinating workshop logistics, speaker sessions, and student founder engagement.",
  },

  // 2. Event Management
  {
    id: "anshuman-katyan-jha",
    slug: "anshuman-katyan-jha",
    name: "Anshuman Katyan Jha",
    role: "Team Lead",
    category: "event_management",
    department: "Computer Science & Engineering (CSE)",
    bio: "Directing OnCampus qualifiers, venue operations, timeline management, and event execution.",
    featured: true,
  },
  {
    id: "soumyadeep-das-mandal",
    slug: "soumyadeep-das-mandal",
    name: "Soumyadeep Das Mandal",
    role: "Team Lead",
    category: "event_management",
    department: "Electronics & Communication Engineering (ECE)",
    bio: "Co-leading stage protocols, logistics, and frictionless operations for the flagship OnCampus competition.",
    featured: true,
  },
  {
    id: "datyatreya-ray",
    slug: "datyatreya-ray",
    name: "Datyatreya Ray",
    role: "Team Member",
    category: "event_management",
    department: "CSE - IoT & Cyber Security (IoTCS)",
    bio: "Managing venue logistics, participant flow, and stage operations for the OnCampus event.",
  },
  {
    id: "sania-parvin",
    slug: "sania-parvin",
    name: "Sania Parvin",
    role: "Team Member",
    category: "event_management",
    department: "Biotechnology (BT)",
    bio: "Coordinating event timelines, day-of-event protocols, and operational delivery for Hult Prize HITK.",
  },

  // 3. Social Media PR and Editing
  {
    id: "soha-alam-mondal",
    slug: "soha-alam-mondal",
    name: "Soha Alam Mondal",
    role: "Team Lead",
    category: "social_pr",
    department: "CSE - Artificial Intelligence & Machine Learning (AIML)",
    bio: "Spearheading social media campaigns, student engagement, and digital outreach for Hult Prize.",
    featured: true,
  },
  {
    id: "kaustavi-mullick",
    slug: "kaustavi-mullick",
    name: "Kaustavi Mullick",
    role: "Team Lead",
    category: "social_pr",
    department: "Biotechnology (BT)",
    bio: "Crafting editorial storytelling, press communication, and multi-channel public relations.",
    featured: true,
  },
  {
    id: "amit-majumder",
    slug: "amit-majumder",
    name: "Amit Majumder",
    role: "Team Member",
    category: "social_pr",
    department: "Electronics & Communication Engineering (ECE)",
    bio: "Curating engaging digital campaigns, reels, and community outreach for Hult Prize HITK.",
  },
  {
    id: "bedantika-sadhukhan",
    slug: "bedantika-sadhukhan",
    name: "Bedantika Sadhukhan",
    role: "Team Member",
    category: "social_pr",
    department: "Biotechnology (BT)",
    bio: "Driving editorial storytelling, caption craft, and public relations across social platforms.",
  },
  {
    id: "titli-ray",
    slug: "titli-ray",
    name: "Titli Ray",
    role: "Team Member",
    category: "social_pr",
    department: "CSE - IoT & Cyber Security (IoTCS)",
    bio: "Managing content calendar, digital promotion, and community engagement for Hult Prize HITK.",
  },
  {
    id: "antarika-roy",
    slug: "antarika-roy",
    name: "Antarika Roy",
    role: "Team Member",
    category: "social_pr",
    department: "CSE - Artificial Intelligence & Machine Learning (AIML)",
    bio: "Crafting creative copywriting, social media announcements, and student outreach campaigns.",
  },

  // 4. Photography
  {
    id: "subhadeep-chanda",
    slug: "subhadeep-chanda",
    name: "Subhadeep Chanda",
    role: "Team Lead",
    category: "photography",
    department: "Electrical Engineering (EE)",
    bio: "Capturing the official visual journey, high-impact portraits, and event photography archives.",
    featured: true,
  },
  {
    id: "somiyo-roy",
    slug: "somiyo-roy",
    name: "Somiyo Roy",
    role: "Team Lead",
    category: "photography",
    department: "Electronics & Communication Engineering (ECE)",
    bio: "Directing event documentation, candid coverage, and media cinematography.",
    featured: true,
  },
  {
    id: "utsa-pal",
    slug: "utsa-pal",
    name: "Utsa Pal",
    role: "Team Member",
    category: "photography",
    department: "Computer Science & Engineering (CSE)",
    bio: "Contributing to visual storytelling, camera operations, and event photo coverage for Hult Prize HITK.",
  },
  {
    id: "suvrojeet-samanta",
    slug: "suvrojeet-samanta",
    name: "Suvrojeet Samanta",
    role: "Team Member",
    category: "photography",
    department: "Civil Engineering (CE)",
    bio: "Documenting high-energy milestones, team portraits, and live competition captures for Hult Prize HITK.",
  },

  // 5. Technical
  {
    id: "harsh-raj",
    slug: "harsh-raj",
    name: "Harsh Raj",
    role: "Technical Lead",
    category: "tech",
    department: "CSE - IoT & Cyber Security",
    academicYear: "Final Year",
    bio: "Transforming ambitious ideas into scalable, beautiful digital platforms and web experiences.",
    socials: {
      linkedin: "https://linkedin.com/in/harsh-raj",
      github: "https://github.com/harsh-raj",
      instagram: "https://instagram.com/harsh_raj",
      email: "harsh@hultprizehitk.com",
    },
    featured: true,
  },
  {
    id: "yogesh-kumar",
    slug: "yogesh-kumar",
    name: "Yogesh Kumar",
    role: "Technical Lead",
    category: "tech",
    department: "Computer Science & Engineering (CSE)",
    bio: "Engineering web architecture, backend automation, and secure platform features for Hult Prize HITK.",
    featured: true,
  },
  {
    id: "aheen-chatterjee",
    slug: "aheen-chatterjee",
    name: "Aheen Chatterjee",
    role: "Team Member",
    category: "tech",
    department: "Computer Science & Business Systems (CSBS)",
    bio: "Building digital platforms, frontend interfaces, and responsive web systems for Hult Prize HITK.",
  },
  {
    id: "sagar-choudhary",
    slug: "sagar-choudhary",
    name: "Sagar Choudhary",
    role: "Team Member",
    category: "tech",
    department: "Computer Science & Engineering (CSE)",
    bio: "Engineering robust web architecture, portal features, and workflow tools for Hult Prize HITK.",
  },

  // 6. Design
  {
    id: "arunima-dutta",
    slug: "arunima-dutta",
    name: "Arunima Dutta",
    role: "Team Lead",
    category: "design",
    department: "Computer Science & Engineering (CSE)",
    bio: "Leading brand identity, UI design, creative layouts, and stage visual aesthetics.",
    featured: true,
  },
  {
    id: "srija-banerjee",
    slug: "srija-banerjee",
    name: "Srija Banerjee",
    role: "Team Lead",
    category: "design",
    department: "Electronics & Communication Engineering (ECE)",
    bio: "Crafting promotional graphics, motion visuals, and brand assets for Hult Prize HITK.",
    featured: true,
  },
  {
    id: "preksha-baid",
    slug: "preksha-baid",
    name: "Preksha Baid",
    role: "Team Member",
    category: "design",
    department: "Computer Science & Engineering (CSE)",
    bio: "Designing captivating visual graphics, social banners, and digital assets for Hult Prize HITK.",
  },
  {
    id: "soumyadeep-gope",
    slug: "soumyadeep-gope",
    name: "Soumyadeep Gope",
    role: "Team Member",
    category: "design",
    department: "CSE - Data Science (DS)",
    bio: "Creating modern UI concepts, brand creatives, and promotional visual media for Hult Prize HITK.",
  },
  {
    id: "faizan-ahmed",
    slug: "faizan-ahmed",
    name: "Faizan Ahmed",
    role: "Team Member",
    category: "design",
    department: "Computer Science & Business Systems (CSBS)",
    bio: "Crafting dynamic brand layouts, stage graphics, and aesthetic illustrations for Hult Prize HITK.",
  },
  {
    id: "archita-rudra",
    slug: "archita-rudra",
    name: "Archita Rudra",
    role: "Team Member",
    category: "design",
    department: "Computer Science & Engineering (CSE)",
    bio: "Producing promotional posters, identity elements, and creative visual collaterals for Hult Prize HITK.",
  },

  // 7. Judges Support
  {
    id: "swagatam-chatterjee",
    slug: "swagatam-chatterjee",
    name: "Swagatam Chatterjee",
    role: "Team Lead",
    category: "judges_support",
    department: "Electronics & Communication Engineering (ECE)",
    bio: "Coordinating jury liaison, evaluation protocols, and VIP guest hospitality.",
    featured: true,
  },
  {
    id: "sohon-ganguly",
    slug: "sohon-ganguly",
    name: "Sohon Ganguly",
    role: "Team Lead",
    category: "judges_support",
    department: "Computer Science & Engineering (CSE)",
    bio: "Managing jury scoring matrices, deliberations, and judge assistance for OnCampus pitch day.",
    featured: true,
  },
  {
    id: "aditya-roy",
    slug: "aditya-roy",
    name: "Aditya Roy",
    role: "Team Member",
    category: "judges_support",
    department: "Computer Science & Engineering (CSE)",
    bio: "Assisting esteemed jury members, evaluation scoring sheets, and VIP hospitality for OnCampus pitch day.",
  },
  {
    id: "satyam-kumar-mishra",
    slug: "satyam-kumar-mishra",
    name: "Satyam Kumar Mishra",
    role: "Team Member",
    category: "judges_support",
    department: "Chemical Engineering (ChE)",
    bio: "Coordinating jury protocols, deliberation coordination, and judge relations for Hult Prize HITK.",
  },
];
